name: GitHub Metrics

on:
  schedule:
    # Mise à jour tous les jours à 2h UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    name: Generate GitHub metrics
    
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Krapaud
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          plugin_lines: yes
          plugin_traffic: yes
          plugin_repositories: yes
          plugin_repositories_featured: Krapaud/holbertonschool-printf, Krapaud/holberton-simple_shell
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: percentage
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_introduction: yes
          plugin_calendar: yes
          plugin_calendar_limit: 1
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
