name: GitHub Profile Summary Cards (Alternative)

on:
  schedule:
    # Mise à jour tous les jours à 2h UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate profile summary cards
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate GitHub Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Krapaud
          COMMIT_BY_ME: false
          EXCLUDE: "[]"
          
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "🤖 Update GitHub Profile Summary Cards"
            git push
          fi
